FROM node:carbon as builder

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package.json .

COPY server/package.json ./server/
COPY server/yarn.lock ./server/

COPY client/package.json ./client/
COPY client/yarn.lock ./client/

# Install any needed packages
RUN npm install
RUN cd client && yarn
RUN cd server && yarn

# Bundle app source
COPY . .

RUN npm run build

# Stage 2 build for creating smaller image
FROM node:carbon-alpine
WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/server .

EXPOSE 8080

CMD [ "npm", "start" ]
